-- Supabase/PostgreSQL schema for the ARAM Mayhem recommendation app.
-- Run this in a Supabase staging project first. Do not run directly against
-- production until the current SQL Server data has been backed up.

begin;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create table if not exists public.app_users (
    id bigint generated by default as identity primary key,
    username varchar(100) not null,
    password_hash varchar(512) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists uq_app_users_username_lower
    on public.app_users (lower(username));

create table if not exists public.user_activity_logs (
    id bigint generated by default as identity primary key,
    username varchar(100) not null,
    category varchar(40) not null,
    title varchar(120) not null,
    detail varchar(500) not null,
    link_url varchar(300),
    created_at timestamptz not null default now(),
    constraint ck_user_activity_logs_local_link
        check (link_url is null or (link_url like '/%' and link_url not like '//%'))
);

create index if not exists ix_user_activity_logs_username_created_at
    on public.user_activity_logs (username, created_at desc, id desc);

create table if not exists public.calculation_history (
    id bigint generated by default as identity primary key,
    username varchar(100) not null,
    formula_type varchar(100) not null,
    input_details varchar(1000) not null,
    result_content varchar(1000) not null,
    created_at timestamptz not null default now()
);

create index if not exists ix_calculation_history_username_created_at
    on public.calculation_history (lower(username), created_at desc, id desc);

create table if not exists public.equipments (
    id bigint generated by default as identity primary key,
    owner_username varchar(100) not null,
    name varchar(100) not null,
    hp integer not null default 0,
    mana integer not null default 0,
    attack integer not null default 0,
    magic_attack integer not null default 0,
    physical_defense integer not null default 0,
    magic_defense integer not null default 0,
    health_regen numeric(10, 2) not null default 0,
    mana_regen numeric(10, 2) not null default 0,
    ability_haste numeric(10, 2) not null default 0,
    attack_speed numeric(10, 2) not null default 0,
    critical_strike_chance numeric(10, 2) not null default 0,
    move_speed integer not null default 0,
    move_speed_percent numeric(10, 2) not null default 0,
    lethality numeric(10, 2) not null default 0,
    armor_penetration_percent numeric(10, 2) not null default 0,
    magic_penetration numeric(10, 2) not null default 0,
    magic_penetration_percent numeric(10, 2) not null default 0,
    life_steal numeric(10, 2) not null default 0,
    omnivamp numeric(10, 2) not null default 0,
    heal_and_shield_power numeric(10, 2) not null default 0,
    tenacity numeric(10, 2) not null default 0,
    price integer not null default 0,
    data_dragon_id varchar(50),
    item_image_url varchar(500),
    item_tags varchar(500),
    item_description varchar(2000),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists uq_equipments_owner_name_lower
    on public.equipments (owner_username, lower(name));

create index if not exists ix_equipments_owner_price_name
    on public.equipments (owner_username, price, name);

create table if not exists public.equipment_loadouts (
    id bigint generated by default as identity primary key,
    owner_username varchar(100) not null,
    loadout_name varchar(100) not null,
    eq1_id bigint references public.equipments(id) on delete set null,
    eq2_id bigint references public.equipments(id) on delete set null,
    eq3_id bigint references public.equipments(id) on delete set null,
    eq4_id bigint references public.equipments(id) on delete set null,
    eq5_id bigint references public.equipments(id) on delete set null,
    eq6_id bigint references public.equipments(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists ix_equipment_loadouts_owner_created_at
    on public.equipment_loadouts (owner_username, created_at desc, id desc);

create table if not exists public.ai_recommendation_cache (
    id bigint generated by default as identity primary key,
    username varchar(256) not null,
    cache_key varchar(64) not null,
    game_title varchar(200) not null,
    core_champion varchar(200) not null,
    current_stage varchar(200),
    augment varchar(500),
    available_items varchar(500),
    notes varchar(1000),
    recommendation_json jsonb not null,
    created_at timestamptz not null default now(),
    last_used_at timestamptz not null default now(),
    hit_count integer not null default 0,
    constraint uq_ai_recommendation_cache_username_cache_key unique (username, cache_key)
);

create index if not exists ix_ai_recommendation_cache_username_last_used_at
    on public.ai_recommendation_cache (username, last_used_at desc, id desc);

create table if not exists public.ai_recommendation_favorites (
    id bigint generated by default as identity primary key,
    username varchar(256) not null,
    input_hash varchar(64) not null,
    title varchar(200) not null,
    game_title varchar(200) not null,
    core_champion varchar(200) not null,
    current_stage varchar(200),
    augment varchar(500),
    available_items varchar(500),
    notes varchar(1000),
    summary varchar(500) not null,
    recommended_items varchar(500) not null,
    recommended_augments varchar(700) not null,
    input_json jsonb not null,
    recommendation_json jsonb not null,
    adopted_count integer not null default 0,
    last_adopted_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_ai_recommendation_favorites_username_input_hash unique (username, input_hash)
);

create index if not exists ix_ai_recommendation_favorites_username_updated_at
    on public.ai_recommendation_favorites (username, updated_at desc, id desc);

create index if not exists ix_ai_recommendation_favorites_username_champion
    on public.ai_recommendation_favorites (username, core_champion);

create index if not exists ix_ai_recommendation_favorites_adopted
    on public.ai_recommendation_favorites (adopted_count desc, last_adopted_at desc)
    include (core_champion, updated_at);

create table if not exists public.lol_aram_guides (
    id bigint generated by default as identity primary key,
    champion_key varchar(100) not null,
    champion_name varchar(100) not null,
    localized_name varchar(100),
    mode_name varchar(100) not null default 'ARAM Mayhem',
    patch_version varchar(50) not null default 'manual',
    role_summary varchar(500) not null,
    core_items varchar(1000) not null,
    situational_items varchar(1000),
    augments varchar(1000),
    summoner_spells varchar(500),
    skill_order varchar(500),
    playstyle_tips varchar(1200),
    positioning_tips varchar(1200),
    weaknesses varchar(1200),
    source_url varchar(1000),
    notes varchar(1200),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_lol_aram_guides_champion_key_mode_name unique (champion_key, mode_name)
);

create index if not exists ix_lol_aram_guides_search
    on public.lol_aram_guides (mode_name, champion_key, champion_name);

create table if not exists public.lol_aram_augment_series (
    id bigint generated by default as identity primary key,
    series_key varchar(100) not null,
    series_name varchar(100) not null,
    description varchar(1000),
    set_bonus_text varchar(1200),
    tags varchar(1000),
    patch_version varchar(50) not null default 'manual',
    source_url varchar(1000),
    notes varchar(1200),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_lol_aram_augment_series_series_key unique (series_key)
);

create table if not exists public.lol_aram_augments (
    id bigint generated by default as identity primary key,
    augment_key varchar(100) not null,
    name varchar(100) not null,
    mode_name varchar(100) not null default 'ARAM Mayhem',
    rarity varchar(50) not null,
    tier varchar(20),
    series_key varchar(100) references public.lol_aram_augment_series(series_key),
    effect_text varchar(1200) not null,
    tags varchar(1000),
    synergy_notes varchar(1200),
    patch_version varchar(50) not null default 'manual',
    source_url varchar(1000),
    notes varchar(1200),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_lol_aram_augments_augment_key_mode_name unique (augment_key, mode_name)
);

create index if not exists ix_lol_aram_augments_rarity_tier
    on public.lol_aram_augments (rarity, tier, name);

create index if not exists ix_lol_aram_augments_series_key
    on public.lol_aram_augments (series_key);

create table if not exists public.lol_aram_items (
    id bigint generated by default as identity primary key,
    item_key varchar(100) not null,
    name varchar(100) not null,
    aliases varchar(500),
    mode_name varchar(100) not null default 'ARAM Mayhem',
    effect_text varchar(1200) not null,
    tags varchar(1000),
    synergy_notes varchar(1200),
    patch_version varchar(50) not null default 'manual',
    source_url varchar(1000),
    notes varchar(1200),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_lol_aram_items_item_key_mode_name unique (item_key, mode_name)
);

create index if not exists ix_lol_aram_items_tags
    on public.lol_aram_items (mode_name, item_key, name);

create table if not exists public.lol_aram_synergy_rules (
    id bigint generated by default as identity primary key,
    rule_name varchar(150) not null,
    boost_augment_key varchar(100),
    series_key varchar(100) references public.lol_aram_augment_series(series_key),
    trigger_tags varchar(1000),
    champion_tags varchar(1000),
    item_tags varchar(1000),
    condition_text varchar(1200) not null,
    recommendation_text varchar(1200) not null,
    priority varchar(20) not null default 'medium',
    patch_version varchar(50) not null default 'manual',
    notes varchar(1200),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists ix_lol_aram_synergy_rules_priority
    on public.lol_aram_synergy_rules (priority, series_key, boost_augment_key);

drop trigger if exists trg_app_users_updated_at on public.app_users;
create trigger trg_app_users_updated_at
before update on public.app_users
for each row execute function public.set_updated_at();

drop trigger if exists trg_equipments_updated_at on public.equipments;
create trigger trg_equipments_updated_at
before update on public.equipments
for each row execute function public.set_updated_at();

drop trigger if exists trg_equipment_loadouts_updated_at on public.equipment_loadouts;
create trigger trg_equipment_loadouts_updated_at
before update on public.equipment_loadouts
for each row execute function public.set_updated_at();

drop trigger if exists trg_ai_recommendation_favorites_updated_at on public.ai_recommendation_favorites;
create trigger trg_ai_recommendation_favorites_updated_at
before update on public.ai_recommendation_favorites
for each row execute function public.set_updated_at();

drop trigger if exists trg_lol_aram_guides_updated_at on public.lol_aram_guides;
create trigger trg_lol_aram_guides_updated_at
before update on public.lol_aram_guides
for each row execute function public.set_updated_at();

drop trigger if exists trg_lol_aram_augment_series_updated_at on public.lol_aram_augment_series;
create trigger trg_lol_aram_augment_series_updated_at
before update on public.lol_aram_augment_series
for each row execute function public.set_updated_at();

drop trigger if exists trg_lol_aram_augments_updated_at on public.lol_aram_augments;
create trigger trg_lol_aram_augments_updated_at
before update on public.lol_aram_augments
for each row execute function public.set_updated_at();

drop trigger if exists trg_lol_aram_items_updated_at on public.lol_aram_items;
create trigger trg_lol_aram_items_updated_at
before update on public.lol_aram_items
for each row execute function public.set_updated_at();

drop trigger if exists trg_lol_aram_synergy_rules_updated_at on public.lol_aram_synergy_rules;
create trigger trg_lol_aram_synergy_rules_updated_at
before update on public.lol_aram_synergy_rules
for each row execute function public.set_updated_at();

alter table public.app_users enable row level security;
alter table public.user_activity_logs enable row level security;
alter table public.calculation_history enable row level security;
alter table public.equipments enable row level security;
alter table public.equipment_loadouts enable row level security;
alter table public.ai_recommendation_cache enable row level security;
alter table public.ai_recommendation_favorites enable row level security;
alter table public.lol_aram_guides enable row level security;
alter table public.lol_aram_augment_series enable row level security;
alter table public.lol_aram_augments enable row level security;
alter table public.lol_aram_items enable row level security;
alter table public.lol_aram_synergy_rules enable row level security;

commit;
